// <auto-generated />
using System;
using JavnoNadmetanjeAgregat.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JavnoNadmetanjeAgregat.Migrations
{
    [DbContext(typeof(JavnoNadmetanjeContext))]
    [Migration("20220220221435_IntialCerete")]
    partial class IntialCerete
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JavnoNadmetanjeAgregat.Entities.JavnoNadmetanjeEntity", b =>
                {
                    b.Property<Guid>("JavnoNadmetanjeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdresaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Izuzeto")
                        .HasColumnType("bit");

                    b.Property<Guid>("KatastarskaOpstinaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Krug")
                        .HasColumnType("int");

                    b.Property<Guid>("KupacID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParcelaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PeriodZakupa")
                        .HasColumnType("int");

                    b.Property<int>("PocetnaCenaPoHektaru")
                        .HasColumnType("int");

                    b.Property<Guid>("StatusID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VisinaDopuneDepozita")
                        .HasColumnType("int");

                    b.Property<DateTime>("VremeKraja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremePocetka")
                        .HasColumnType("datetime2");

                    b.HasKey("JavnoNadmetanjeID");

                    b.HasIndex("StatusID");

                    b.HasIndex("TipID");

                    b.ToTable("JavnaNadmetanja");

                    b.HasData(
                        new
                        {
                            JavnoNadmetanjeID = new Guid("3bd80c2a-c790-402f-b214-e3ebbc29d89f"),
                            AdresaID = new Guid("9a8e31d5-5e7b-46e7-80c6-f22e607ee907"),
                            Datum = new DateTime(2021, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Izuzeto = false,
                            KatastarskaOpstinaID = new Guid("3bd80c2a-c790-402f-b214-e3ebbc29d89f"),
                            Krug = 2,
                            KupacID = new Guid("2a411c13-a195-48f7-8dbc-67596c3974c0"),
                            ParcelaID = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            PeriodZakupa = 2,
                            PocetnaCenaPoHektaru = 1000,
                            StatusID = new Guid("bf50e668-c01a-46e3-bae8-a1691c23c65f"),
                            TipID = new Guid("4d51c54c-4b90-46de-8bb2-c8f74fb6fd9e"),
                            VisinaDopuneDepozita = 10,
                            VremeKraja = new DateTime(2021, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VremePocetka = new DateTime(2021, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            JavnoNadmetanjeID = new Guid("7c7764e0-27a2-4123-9eb4-081c4e9bcdbf"),
                            AdresaID = new Guid("9a8e31d5-5e7b-46e7-80c6-f22e607ee907"),
                            Datum = new DateTime(2021, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Izuzeto = false,
                            KatastarskaOpstinaID = new Guid("3bd80c2a-c790-402f-b214-e3ebbc29d89f"),
                            Krug = 2,
                            KupacID = new Guid("2a411c13-a195-48f7-8dbc-67596c3974c0"),
                            ParcelaID = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            PeriodZakupa = 2,
                            PocetnaCenaPoHektaru = 1000,
                            StatusID = new Guid("bf50e668-c01a-46e3-bae8-a1691c23c65f"),
                            TipID = new Guid("4d51c54c-4b90-46de-8bb2-c8f74fb6fd9e"),
                            VisinaDopuneDepozita = 10,
                            VremeKraja = new DateTime(2021, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VremePocetka = new DateTime(2021, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("JavnoNadmetanjeAgregat.Entities.SluzbeniListEntity", b =>
                {
                    b.Property<Guid>("SluzbeniListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrojSluzbenogLista")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumIzdavanjaSluzbenogLista")
                        .HasColumnType("datetime2");

                    b.Property<string>("Opstina")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SluzbeniListID");

                    b.ToTable("SluzbeniListovi");

                    b.HasData(
                        new
                        {
                            SluzbeniListID = new Guid("102e134d-ffde-40fa-b355-f0b8bc52f886"),
                            BrojSluzbenogLista = 12,
                            DatumIzdavanjaSluzbenogLista = new DateTime(2021, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Opstina = "Beograd"
                        },
                        new
                        {
                            SluzbeniListID = new Guid("901b0ad2-6aa8-4076-8162-01b3a42f2a2e"),
                            BrojSluzbenogLista = 13,
                            DatumIzdavanjaSluzbenogLista = new DateTime(2021, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Opstina = "Novi Sad"
                        });
                });

            modelBuilder.Entity("JavnoNadmetanjeAgregat.Entities.StatusJavnogNadmetanjaEntity", b =>
                {
                    b.Property<Guid>("StatusJavnogNadmetanjaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivStatusaJavnogNadmetanja")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusJavnogNadmetanjaID");

                    b.ToTable("StatusiJavnihNadmetanja");

                    b.HasData(
                        new
                        {
                            StatusJavnogNadmetanjaID = new Guid("bf50e668-c01a-46e3-bae8-a1691c23c65f"),
                            NazivStatusaJavnogNadmetanja = "Status1"
                        },
                        new
                        {
                            StatusJavnogNadmetanjaID = new Guid("b38e3b4f-5539-4475-8424-00ca7a59e496"),
                            NazivStatusaJavnogNadmetanja = "Status2"
                        });
                });

            modelBuilder.Entity("JavnoNadmetanjeAgregat.Entities.TipJavnogNadmetanjaEntity", b =>
                {
                    b.Property<Guid>("TipJavnogNadmetanjaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivTipaJavnogNadmetanja")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipJavnogNadmetanjaID");

                    b.ToTable("TipoviJavnihNadmetanja");

                    b.HasData(
                        new
                        {
                            TipJavnogNadmetanjaID = new Guid("4d51c54c-4b90-46de-8bb2-c8f74fb6fd9e"),
                            NazivTipaJavnogNadmetanja = "Tip1"
                        },
                        new
                        {
                            TipJavnogNadmetanjaID = new Guid("0f173f98-c00a-4eb4-8131-ae00177371d8"),
                            NazivTipaJavnogNadmetanja = "Tip2"
                        });
                });

            modelBuilder.Entity("JavnoNadmetanjeAgregat.Entities.JavnoNadmetanjeEntity", b =>
                {
                    b.HasOne("JavnoNadmetanjeAgregat.Entities.StatusJavnogNadmetanjaEntity", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JavnoNadmetanjeAgregat.Entities.TipJavnogNadmetanjaEntity", "Tip")
                        .WithMany()
                        .HasForeignKey("TipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Tip");
                });
#pragma warning restore 612, 618
        }
    }
}
