// <auto-generated />
using System;
using KatastarskaOpstinaAgregat.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KatastarskaOpstinaAgregat.Migrations
{
    [DbContext(typeof(KatastarskaOpstinaContext))]
    partial class KatastarskaOpstinaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KatastarskaOpstinaAgregat.Entities.KatastarskaOpstinaEntity", b =>
                {
                    b.Property<Guid>("KatastarskaOpstinaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivKatastarskeOpstine")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KatastarskaOpstinaID");

                    b.ToTable("KatastarskeOpstine");

                    b.HasData(
                        new
                        {
                            KatastarskaOpstinaID = new Guid("3bd80c2a-c790-402f-b214-e3ebbc29d89f"),
                            NazivKatastarskeOpstine = "Beocin"
                        },
                        new
                        {
                            KatastarskaOpstinaID = new Guid("177e64ad-2ff0-4a40-9c75-1f9b02ffe1e9"),
                            NazivKatastarskeOpstine = "Beograd"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
