// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uplata.Entities;

namespace Uplata.Migrations
{
    [DbContext(typeof(UplataContext))]
    [Migration("20220207143602_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Uplata.Entities.UplataModel", b =>
                {
                    b.Property<Guid>("UplataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Iznos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JavnoNadmetanjeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KupacID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PozivNaBroj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SvrhaUplate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UplataID");

                    b.ToTable("Uplate");

                    b.HasData(
                        new
                        {
                            UplataID = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            Datum = new DateTime(2022, 2, 7, 15, 36, 2, 89, DateTimeKind.Local).AddTicks(6851),
                            Iznos = "150000",
                            JavnoNadmetanjeID = new Guid("6a411c23-a192-48f7-8dbd-67596c3974c0"),
                            KupacID = new Guid("6a411c23-a195-48f7-8dbd-67596c3974c0"),
                            PozivNaBroj = "3121-424324523-444",
                            SvrhaUplate = "ucesce na licitaciji"
                        },
                        new
                        {
                            UplataID = new Guid("7a411c13-a195-48f7-8dbd-67596c3974c0"),
                            Datum = new DateTime(2022, 2, 7, 15, 36, 2, 91, DateTimeKind.Local).AddTicks(9895),
                            Iznos = "200000",
                            JavnoNadmetanjeID = new Guid("6a411c23-a192-48f7-8dbd-67596c3974c0"),
                            KupacID = new Guid("6a411c23-a195-48f7-8dbd-67596c3974c0"),
                            PozivNaBroj = "0242-424324523-444",
                            SvrhaUplate = "ucesce na licitaciji"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
