// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uplata.Entities;

namespace Uplata.Migrations
{
    [DbContext(typeof(UplataContext))]
    [Migration("20220221185426_InitialCreateUplata")]
    partial class InitialCreateUplata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Uplata.Entities.UplataEntity", b =>
                {
                    b.Property<Guid>("UplataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojRacuna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Iznos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("JavnoNadmetanjeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PozivNaBroj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SvrhaUplate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UplataID");

                    b.ToTable("Uplata");

                    b.HasData(
                        new
                        {
                            UplataID = new Guid("8d452221-f73e-4e35-ba7c-3fdd0d08be70"),
                            BrojRacuna = "155-228523852256500-25",
                            Datum = new DateTime(2022, 2, 21, 19, 54, 25, 671, DateTimeKind.Local).AddTicks(7368),
                            Iznos = "150000",
                            PozivNaBroj = "3121-424324523-444",
                            SvrhaUplate = "ucesce na licitaciji"
                        },
                        new
                        {
                            UplataID = new Guid("5f951cf9-aaf2-45c3-823a-5c8c4c1deaff"),
                            BrojRacuna = "155-228523852256500-25",
                            Datum = new DateTime(2022, 2, 21, 19, 54, 25, 686, DateTimeKind.Local).AddTicks(8867),
                            Iznos = "200000",
                            PozivNaBroj = "0242-424324523-444",
                            SvrhaUplate = "ucesce na licitaciji"
                        });
                });

            modelBuilder.Entity("Uplata.Entities.UplataEntity", b =>
                {
                    b.OwnsOne("Uplata.Entities.Kurs", "Kurs", b1 =>
                        {
                            b1.Property<Guid>("UplataEntityUplataID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Datum")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Valuta")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("VrednostKursa")
                                .HasColumnType("float");

                            b1.HasKey("UplataEntityUplataID");

                            b1.ToTable("Uplata");

                            b1.WithOwner()
                                .HasForeignKey("UplataEntityUplataID");
                        });

                    b.Navigation("Kurs");
                });
#pragma warning restore 612, 618
        }
    }
}
