// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uplata.Entities;

namespace Uplata.Migrations
{
    [DbContext(typeof(UplataContext))]
    partial class UplataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Uplata.Entities.KursEntity", b =>
                {
                    b.Property<Guid>("KursID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Valuta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("VrednostKursa")
                        .HasColumnType("float");

                    b.HasKey("KursID");

                    b.ToTable("Kursevi");

                    b.HasData(
                        new
                        {
                            KursID = new Guid("b06a4284-44e2-46af-8d74-b79c8b0c6017"),
                            Datum = new DateTime(2022, 2, 23, 13, 30, 45, 616, DateTimeKind.Local).AddTicks(6713),
                            Valuta = "EUR",
                            VrednostKursa = 117.8
                        },
                        new
                        {
                            KursID = new Guid("411c4082-cc5e-4f5f-8946-4086ebca08d0"),
                            Datum = new DateTime(2022, 2, 23, 13, 30, 45, 618, DateTimeKind.Local).AddTicks(8642),
                            Valuta = "GBT",
                            VrednostKursa = 150.5
                        });
                });

            modelBuilder.Entity("Uplata.Entities.UplataEntity", b =>
                {
                    b.Property<Guid>("UplataID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojRacuna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Iznos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("JavnoNadmetanjeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KursID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PozivNaBroj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SvrhaUplate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UplataID");

                    b.HasIndex("KursID");

                    b.ToTable("Uplate");

                    b.HasData(
                        new
                        {
                            UplataID = new Guid("8d452221-f73e-4e35-ba7c-3fdd0d08be70"),
                            BrojRacuna = "155-228523852256500-25",
                            Datum = new DateTime(2022, 2, 23, 13, 30, 45, 618, DateTimeKind.Local).AddTicks(8783),
                            Iznos = "200",
                            KursID = new Guid("411c4082-cc5e-4f5f-8946-4086ebca08d0"),
                            PozivNaBroj = "3121-424324523-444",
                            SvrhaUplate = "ucesce na licitaciji"
                        },
                        new
                        {
                            UplataID = new Guid("5f951cf9-aaf2-45c3-823a-5c8c4c1deaff"),
                            BrojRacuna = "155-228523852256500-25",
                            Datum = new DateTime(2022, 2, 23, 13, 30, 45, 618, DateTimeKind.Local).AddTicks(9598),
                            Iznos = "100",
                            KursID = new Guid("b06a4284-44e2-46af-8d74-b79c8b0c6017"),
                            PozivNaBroj = "0242-424324523-444",
                            SvrhaUplate = "ucesce na licitaciji"
                        },
                        new
                        {
                            UplataID = new Guid("1d2ed242-5059-4a1b-aeab-eee99404284f"),
                            BrojRacuna = "115-228523852256500-25",
                            Datum = new DateTime(2022, 2, 23, 13, 30, 45, 618, DateTimeKind.Local).AddTicks(9628),
                            Iznos = "50",
                            KursID = new Guid("411c4082-cc5e-4f5f-8946-4086ebca08d0"),
                            PozivNaBroj = "3221-424324523-444",
                            SvrhaUplate = "ucesce na licitaciji"
                        });
                });

            modelBuilder.Entity("Uplata.Entities.UplataEntity", b =>
                {
                    b.HasOne("Uplata.Entities.KursEntity", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");
                });
#pragma warning restore 612, 618
        }
    }
}
