// <auto-generated />
using System;
using ComplaintAggregate.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComplaintAggregate.Migrations
{
    [DbContext(typeof(ComplaintAggregateContext))]
    [Migration("20220128204113_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComplaintAggregate.Entities.Complaint", b =>
                {
                    b.Property<Guid>("ZalbaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Broj_nadmetanja")
                        .HasColumnType("int");

                    b.Property<int>("Broj_rijesenja")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum_podnosenja_zalbe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Datum_rijesenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Obrazlozenje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Razlog_zalbe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZalbaID");

                    b.ToTable("Complaints");

                    b.HasData(
                        new
                        {
                            ZalbaID = new Guid("efbb80d6-e57b-4e45-9216-e23fc1de805b"),
                            Broj_nadmetanja = 32,
                            Broj_rijesenja = 23,
                            Datum_podnosenja_zalbe = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Datum_rijesenja = new DateTime(2011, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Obrazlozenje = "obrazlozenje",
                            Razlog_zalbe = "razlog"
                        },
                        new
                        {
                            ZalbaID = new Guid("5742a2d4-5ebc-466d-99ba-25d8d8dcd082"),
                            Broj_nadmetanja = 32,
                            Broj_rijesenja = 23,
                            Datum_podnosenja_zalbe = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Datum_rijesenja = new DateTime(2012, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Obrazlozenje = "obrazlozenje2",
                            Razlog_zalbe = "razlog2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
