// <auto-generated />
using System;
using Licitacija.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Licitacija.Migrations
{
    [DbContext(typeof(LicitacijaContext))]
    [Migration("20220222132321_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Licitacija.Entities.LicitacijaEntity", b =>
                {
                    b.Property<Guid>("LicitacijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Broj")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("DokFizickog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DokPravnog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Godina")
                        .HasColumnType("int");

                    b.Property<Guid?>("JavnoNadmetanjeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KorakCene")
                        .HasColumnType("int");

                    b.Property<Guid?>("KupacID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ogranicenje")
                        .HasColumnType("int");

                    b.Property<DateTime>("Rok")
                        .HasColumnType("datetime2");

                    b.HasKey("LicitacijaID");

                    b.ToTable("Licitacije");

                    b.HasData(
                        new
                        {
                            LicitacijaID = new Guid("8d452221-f73e-4e35-ba7c-3fdd0d08be70"),
                            Broj = 1,
                            Datum = new DateTime(2022, 2, 22, 14, 23, 20, 874, DateTimeKind.Local).AddTicks(5198),
                            DokFizickog = "Dokument1",
                            DokPravnog = "Dokument1",
                            Godina = 2002,
                            JavnoNadmetanjeID = new Guid("8d452221-f73e-4e35-ba7c-3fdd0d08be70"),
                            KorakCene = 100,
                            KupacID = new Guid("1a411c13-a195-48f7-8dbd-67596c3974c0"),
                            Ogranicenje = 100,
                            Rok = new DateTime(2022, 2, 22, 14, 23, 20, 875, DateTimeKind.Local).AddTicks(9164)
                        },
                        new
                        {
                            LicitacijaID = new Guid("4879ec40-df11-457c-9bd1-07cd2b4ec7cd"),
                            Broj = 2,
                            Datum = new DateTime(2022, 2, 22, 14, 23, 20, 876, DateTimeKind.Local).AddTicks(7922),
                            DokFizickog = "Dokument2",
                            DokPravnog = "Dokument2",
                            Godina = 2020,
                            JavnoNadmetanjeID = new Guid("8d452221-f73e-4e35-ba7c-3fdd0d08be70"),
                            KorakCene = 200,
                            KupacID = new Guid("1a411c13-a195-48f7-8dbd-67596c3974c0"),
                            Ogranicenje = 200,
                            Rok = new DateTime(2022, 2, 22, 14, 23, 20, 876, DateTimeKind.Local).AddTicks(7936)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
