// <auto-generated />
using System;
using Licnost.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Licnost.Migrations
{
    [DbContext(typeof(LicnostContext))]
    [Migration("20220222161840_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Licnost.Entities.ClanKomisije", b =>
                {
                    b.Property<Guid>("ClanKomisijeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KomisijaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LicnostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClanKomisijeId");

                    b.HasIndex("KomisijaId");

                    b.HasIndex("LicnostId");

                    b.ToTable("ClanoviKomisije");

                    b.HasData(
                        new
                        {
                            ClanKomisijeId = new Guid("049c45e5-8873-49c2-8275-0b63293f15e7"),
                            KomisijaId = new Guid("3540bf55-427a-4892-91d6-633d683ef0ed"),
                            LicnostId = new Guid("218c05c6-5066-4354-9568-b263ab11713b")
                        });
                });

            modelBuilder.Entity("Licnost.Entities.Komisija", b =>
                {
                    b.Property<Guid>("KomisijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LicnostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KomisijaId");

                    b.HasIndex("LicnostId");

                    b.ToTable("Komisije");

                    b.HasData(
                        new
                        {
                            KomisijaId = new Guid("3540bf55-427a-4892-91d6-633d683ef0ed"),
                            LicnostId = new Guid("e91b29cc-79a5-4de8-8030-77df6e514def")
                        });
                });

            modelBuilder.Entity("Licnost.Entities.LicnostEntity", b =>
                {
                    b.Property<Guid>("LicnostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LicnostFunkcija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicnostIme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicnostPrezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicnostId");

                    b.ToTable("Licnosti");

                    b.HasData(
                        new
                        {
                            LicnostId = new Guid("e91b29cc-79a5-4de8-8030-77df6e514def"),
                            LicnostFunkcija = "IT",
                            LicnostIme = "Simona",
                            LicnostPrezime = "Bolehradsky"
                        },
                        new
                        {
                            LicnostId = new Guid("218c05c6-5066-4354-9568-b263ab11713b"),
                            LicnostFunkcija = "Direktor",
                            LicnostIme = "Dajana",
                            LicnostPrezime = "Jelic"
                        });
                });

            modelBuilder.Entity("Licnost.Entities.ClanKomisije", b =>
                {
                    b.HasOne("Licnost.Entities.Komisija", "Komisija")
                        .WithMany()
                        .HasForeignKey("KomisijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Licnost.Entities.LicnostEntity", "Licnost")
                        .WithMany()
                        .HasForeignKey("LicnostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Komisija");

                    b.Navigation("Licnost");
                });

            modelBuilder.Entity("Licnost.Entities.Komisija", b =>
                {
                    b.HasOne("Licnost.Entities.LicnostEntity", "Licnost")
                        .WithMany()
                        .HasForeignKey("LicnostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Licnost");
                });
#pragma warning restore 612, 618
        }
    }
}
